import type { Language } from "@/lib/types";

const copies = {
  en: {
    pages: "Pages",
    page: "Page",
    pageTitle: "Page title",
    pageTitleRequired: "Enter a page title.",
    pageDescription: "Page description",
    pageDescriptionPlaceholder: "Optional context for this step",
    addPage: "Add page",
    removePage: "Remove page",
    movePageUp: "Move page left",
    movePageDown: "Move page right",
    dragPage: "Drag to reorder page",
    fieldPage: "Page",
    fields: "fields",
    emptyPage: "This page has no fields yet.",
    pageDropHint: "Drag a field onto another page tab to move it there.",
    version: "Version",
    draft: "Draft",
    published: "Published",
    archived: "Archived",
    saveDraft: "Save draft",
    publish: "Publish",
    publishing: "Publishing...",
    publishUnavailable: "Connect the version adapter publish callback to enable publishing.",
    alreadyPublished: "This version is already published.",
    archivedVersion: "Edit this archived version to create a new draft.",
    layoutPersistenceUnavailable: "Page and version metadata stays local until the version adapter is connected.",
    draftSaved: "Draft version saved.",
    publishedMessage: "Version published.",
    archive: "Archive",
    archiving: "Archiving...",
    archiveConfirmTitle: "Archive this version?",
    archiveConfirmDescription: "This published version will no longer be available for starting new processes. Existing processes keep their pinned version.",
    archiveConfirm: "Archive version",
    archivedMessage: "Version archived.",
    stepperLabel: "Form pages",
    previous: "Previous",
    next: "Next",
    goToPage: "Go to page",
    pageProgress: "Page {current} of {total}",
    pageErrors: "Complete this page before continuing.",
    draftUnavailable: "This form version is still a draft and cannot be started.",
    archivedUnavailable: "This archived form version cannot be started.",
  },
  tr: {
    pages: "Sayfalar",
    page: "Sayfa",
    pageTitle: "Sayfa başlığı",
    pageTitleRequired: "Bir sayfa başlığı girin.",
    pageDescription: "Sayfa açıklaması",
    pageDescriptionPlaceholder: "Bu adım için isteğe bağlı açıklama",
    addPage: "Sayfa ekle",
    removePage: "Sayfayı kaldır",
    movePageUp: "Sayfayı sola taşı",
    movePageDown: "Sayfayı sağa taşı",
    dragPage: "Sayfayı yeniden sıralamak için sürükleyin",
    fieldPage: "Sayfa",
    fields: "alan",
    emptyPage: "Bu sayfada henüz alan yok.",
    pageDropHint: "Bir alanı başka bir sayfa sekmesine sürükleyerek taşıyın.",
    version: "Sürüm",
    draft: "Taslak",
    published: "Yayında",
    archived: "Arşivlendi",
    saveDraft: "Taslağı kaydet",
    publish: "Yayınla",
    publishing: "Yayınlanıyor...",
    publishUnavailable: "Yayınlamayı etkinleştirmek için sürüm adaptörünün publish callback'ini bağlayın.",
    alreadyPublished: "Bu sürüm zaten yayında.",
    archivedVersion: "Yeni bir taslak oluşturmak için arşivlenmiş bu sürümü düzenleyin.",
    layoutPersistenceUnavailable: "Sürüm adaptörü bağlanana kadar sayfa ve sürüm bilgileri yerel kalır.",
    draftSaved: "Taslak sürüm kaydedildi.",
    publishedMessage: "Sürüm yayınlandı.",
    archive: "Arşivle",
    archiving: "Arşivleniyor...",
    archiveConfirmTitle: "Bu sürüm arşivlensin mi?",
    archiveConfirmDescription: "Bu yayın sürümü yeni süreç başlatmak için kullanılamayacak. Çalışan süreçler sabitlenmiş sürümleriyle devam edecek.",
    archiveConfirm: "Sürümü arşivle",
    archivedMessage: "Sürüm arşivlendi.",
    stepperLabel: "Form sayfaları",
    previous: "Önceki",
    next: "Sonraki",
    goToPage: "Sayfaya git",
    pageProgress: "{total} sayfanın {current}. sayfası",
    pageErrors: "Devam etmeden önce bu sayfayı tamamlayın.",
    draftUnavailable: "Bu form sürümü hâlâ taslak olduğu için başlatılamaz.",
    archivedUnavailable: "Arşivlenmiş bu form sürümü başlatılamaz.",
  },
} as const;

export function getFormPagingCopy(language: Language) {
  return copies[language];
}

export function formatPagingCopy(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce(
    (current, [key, value]) => current.replaceAll(`{${key}}`, String(value)),
    template,
  );
}
