// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechYouthBpm.Infrastructure.Data;

#nullable disable

namespace TechYouthBpm.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716144938_AddStructuredSystemAudit")]
    partial class AddStructuredSystemAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.CommunityRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId", "Name")
                        .IsUnique();

                    b.ToTable("CommunityRoles");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.CommunityRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityRoleId", "Permission")
                        .IsUnique();

                    b.ToTable("CommunityRolePermissions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FieldValidationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DependsOnFieldKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FormFieldDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormFieldDefinitionId");

                    b.ToTable("FieldValidationRules");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("FormDefinitions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("FormDefinitionId", "Status");

                    b.HasIndex("FormDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("FormDefinitionVersions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormDefinitionId");

                    b.ToTable("FormFieldDefinitions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormPageDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FormDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormDefinitionVersionId", "Key")
                        .IsUnique();

                    b.HasIndex("FormDefinitionVersionId", "SortOrder");

                    b.ToTable("FormPageDefinitions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormVersionFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormPageDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormPageDefinitionId", "Key")
                        .IsUnique();

                    b.ToTable("FormVersionFieldDefinitions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormVersionFieldValidationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DependsOnFieldKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FormVersionFieldDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormVersionFieldDefinitionId");

                    b.ToTable("FormVersionFieldValidationRules");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "ReadAt", "CreatedAt");

                    b.HasIndex("UserId", "Type", "ReadAt", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CommunityId", "Name");

                    b.ToTable("ProcessDefinitions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("GraphJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FormDefinitionVersionId");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("ProcessDefinitionId", "Status");

                    b.HasIndex("ProcessDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ProcessDefinitionVersions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentNodeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FormDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FormDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProcessDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StartedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VariablesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("FormDefinitionId");

                    b.HasIndex("FormDefinitionVersionId");

                    b.HasIndex("ProcessDefinitionVersionId");

                    b.HasIndex("StartedByUserId");

                    b.ToTable("ProcessInstances");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessStepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Action")
                        .HasColumnType("integer");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("ProcessInstanceId", "NodeKey", "Attempt")
                        .IsUnique();

                    b.ToTable("ProcessStepExecutions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedCommunityRoleId")
                        .HasColumnType("uuid");

                    b.Property<int>("AssignedRole")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AssignmentType")
                        .HasColumnType("integer");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<string>("AvailableActionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CandidateCommunityRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CandidateTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FormDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcessInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequiredPermission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCommunityRoleId");

                    b.HasIndex("CandidateCommunityRoleId");

                    b.HasIndex("CandidateTeamId");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("FormDefinitionVersionId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("AssignedUserId", "Status");

                    b.HasIndex("ClaimedByUserId", "Status");

                    b.HasIndex("Status", "DueAt", "Priority", "CreatedAt");

                    b.ToTable("ProcessTasks");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIpAddress")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserAgent")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByRefreshTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserSessionId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.SystemAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CommunityId", "Category", "CreatedAt");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CommunityId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("TeamMemberships");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerificationCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.UserCommunityMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityRoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("CommunityRoleId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("UserCommunityMemberships");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RememberedDevice")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.ProcessInstance", "ProcessInstance")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.CommunityRole", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.Community", "Community")
                        .WithMany("Roles")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.CommunityRolePermission", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.CommunityRole", "CommunityRole")
                        .WithMany("Permissions")
                        .HasForeignKey("CommunityRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunityRole");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FieldValidationRule", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.FormFieldDefinition", "Field")
                        .WithMany("ValidationRules")
                        .HasForeignKey("FormFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormDefinition", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormDefinitionVersion", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.FormDefinition", "FormDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("FormDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("FormDefinition");

                    b.Navigation("PublishedByUser");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormFieldDefinition", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.FormDefinition", "FormDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("FormDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormDefinition");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormPageDefinition", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.FormDefinitionVersion", "FormDefinitionVersion")
                        .WithMany("Pages")
                        .HasForeignKey("FormDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormDefinitionVersion");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormVersionFieldDefinition", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.FormPageDefinition", "FormPageDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("FormPageDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormPageDefinition");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormVersionFieldValidationRule", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.FormVersionFieldDefinition", "Field")
                        .WithMany("ValidationRules")
                        .HasForeignKey("FormVersionFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessDefinition", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessDefinitionVersion", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.FormDefinitionVersion", "FormDefinitionVersion")
                        .WithMany()
                        .HasForeignKey("FormDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("FormDefinitionVersion");

                    b.Navigation("ProcessDefinition");

                    b.Navigation("PublishedByUser");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessInstance", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.FormDefinition", "FormDefinition")
                        .WithMany()
                        .HasForeignKey("FormDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.FormDefinitionVersion", "FormDefinitionVersion")
                        .WithMany()
                        .HasForeignKey("FormDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechYouthBpm.Domain.Entities.ProcessDefinitionVersion", "ProcessDefinitionVersion")
                        .WithMany()
                        .HasForeignKey("ProcessDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "StartedByUser")
                        .WithMany()
                        .HasForeignKey("StartedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("FormDefinition");

                    b.Navigation("FormDefinitionVersion");

                    b.Navigation("ProcessDefinitionVersion");

                    b.Navigation("StartedByUser");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessStepExecution", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechYouthBpm.Domain.Entities.ProcessInstance", "ProcessInstance")
                        .WithMany("StepExecutions")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedByUser");

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessTask", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.CommunityRole", "AssignedCommunityRole")
                        .WithMany()
                        .HasForeignKey("AssignedCommunityRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechYouthBpm.Domain.Entities.CommunityRole", "CandidateCommunityRole")
                        .WithMany()
                        .HasForeignKey("CandidateCommunityRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechYouthBpm.Domain.Entities.Team", "CandidateTeam")
                        .WithMany()
                        .HasForeignKey("CandidateTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "ClaimedByUser")
                        .WithMany()
                        .HasForeignKey("ClaimedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId");

                    b.HasOne("TechYouthBpm.Domain.Entities.FormDefinitionVersion", "FormDefinitionVersion")
                        .WithMany()
                        .HasForeignKey("FormDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechYouthBpm.Domain.Entities.ProcessInstance", "ProcessInstance")
                        .WithMany("Tasks")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedCommunityRole");

                    b.Navigation("AssignedUser");

                    b.Navigation("CandidateCommunityRole");

                    b.Navigation("CandidateTeam");

                    b.Navigation("ClaimedByUser");

                    b.Navigation("CompletedByUser");

                    b.Navigation("FormDefinitionVersion");

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.UserSession", "UserSession")
                        .WithMany()
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.SystemAuditLog", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechYouthBpm.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.Team", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.Community", "Community")
                        .WithMany("Teams")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.TeamMembership", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.Team", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.UserCommunityMembership", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.CommunityRole", "CommunityRole")
                        .WithMany()
                        .HasForeignKey("CommunityRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechYouthBpm.Domain.Entities.User", "User")
                        .WithMany("CommunityMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("CommunityRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("TechYouthBpm.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.Community", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.CommunityRole", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormDefinitionVersion", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormFieldDefinition", b =>
                {
                    b.Navigation("ValidationRules");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormPageDefinition", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.FormVersionFieldDefinition", b =>
                {
                    b.Navigation("ValidationRules");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.ProcessInstance", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("StepExecutions");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.Team", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("TechYouthBpm.Domain.Entities.User", b =>
                {
                    b.Navigation("CommunityMemberships");

                    b.Navigation("TeamMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
